### ISSUE TITLE
[question] Does parquet4 support partitioning?

### ISSUE THREAD

**Issue by battermann** [mjakubowski84/parquet4s#106]
Hi,

does parquet4s support partitioning?
E.g. by date: `some_key/year=2019/month=9/day=24/`

I think this could be quite tedious to implement, if not supported by the lib. If possible at all?

Context: I'm trying to replace a Spark job that reads from Kafka and writes to S3 with an Akka Streams application.

Thanks!

**Comment by mjakubowski84** [comment]
Hi Leif!
Core library does not support partitioning. I believe you want to have a look at provided example app that indefinitely reads from Kafka using Akka Streams. Example https://github.com/mjakubowski84/parquet4s/blob/master/examples/src/main/scala/com/github/mjakubowski84/parquet4s/MessageSink.scala already provides naive solution for saving files in partitions. However, example assumes that data arrives to Kafka in ordered manner (by values that we want to partition by). Still, there are solutions in Akka Stream to solve it - e.g. Partition graph operator or  groupBy function.
I think that that partitioning functionality might be too much fas or core module. Akka allows to partition streams using its API. You can use what Akka provides. 
And if you wish to extends IndefiniteStream Sink with such optional feature - you are warmly welcome!
