### ISSUE TITLE
Support for reading and writing mutable version of Scala collection

### ISSUE THREAD

**Issue by mjakubowski84** [mjakubowski84/parquet4s#109]
If anybody would really need this functionality then this issue can be addressed.

At this moment the library allows only to define immutable collections in case class schema. Support for collections like list, seq, array, etc. can be added by developer on their own by defining own `CollectionTransformer` (https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/CollectionTransformer.scala).
Regarding Map there would be need to define own `ValueCodec`.
Library can provide such functionality out of the box.

**Comment by mjakubowski84** [comment]
Since 1.2.0 there is no collection transformer. Parquet4S already supports mutable collections, except mutable Map.
Please note that Spark does not support mutable collections as a schema but Parquet4S does.

**Comment by mjakubowski84** [comment]
Closing this for now

**Comment by q-llewellynthomas** [comment]
@mjakubowski84 I'm stuck on 1.9.4 and won't be able to upgrade due to other dependencies.

Is there any way to implement a mutable map? I have a data structure I cannot change that contains a mutable map that I need to write to a parquet file.

Thanks
