### ISSUE TITLE
com.github.mjakubowski84.parquet4s.{ParquetStreams} class file missing in latest Jar

### ISSUE THREAD

**Issue by AjitTK** [mjakubowski84/parquet4s#112]
While trying to execute basic example code ,I Unable to find ParquetStreams class in latest jar.

**Comment by mjakubowski84** [comment]
I can't check it now on my own, but did you add `"com.github.mjakubowski84" %% "parquet4s-akka" % "0.10.0"` to your dependencies?

**Comment by AjitTK** [comment]
Thank you for quick reply 
with "com.github.mjakubowski84" %% "parquet4s-akka" % "0.10.0" its working , but I was referring documentation where "com.github.mjakubowski84" %% "parquet4s-core" % "0.10.0" is mentioned.
