### ISSUE TITLE
Parquet file sync with s3 not working and not even showing exception or error

### ISSUE THREAD

**Issue by AjitTK** [mjakubowski84/parquet4s#115]
I tried with Environment variable of AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY in Intellij and run the code but its not doing sync of file on s3 where as on local is working fine.
And its not even showing error or exception.

**Comment by mjakubowski84** [comment]
Please read here https://hadoop.apache.org/docs/current/hadoop-aws/tools/hadoop-aws/index.html how you connect to AWS using Hadoop. I just added that link to ReadMe. Parquet is based on Hadoop and all what refers to connecting to storage is handled by Hadoop modules.

**Comment by mjakubowski84** [comment]
Please check if you added hadoop-aws dependency as stated in ReadMe and if you still have issues then follow the documentation of Hadoop Client

**Comment by AjitTK** [comment]
Even after including jars and Hadoop configuration I wont be able to debug issue. There is no exception is thrown during write.

**Comment by AjitTK** [comment]
Ok , After doing some search and correcting some mistakes I am able to sync files on s3

For hadoop configuration I have create Hadoop config object 

```
val config = new Configuration()
  config.set("fs.s3.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
  config.set("fs.s3.awsAccessKeyId", " ............AWSAccessKeyId...........")
  config.set("fs.s3.awsSecretAccessKey", ".........AWSSecretKey................")
```
and Updated writeOptions 
```
 val writeOptions = ParquetWriter.Options(
    writeMode = ParquetFileWriter.Mode.OVERWRITE,
    compressionCodecName = CompressionCodecName.SNAPPY,
    hadoopConf = config
  )
```

The mistake I did was , before parquet file upload I was termination akka system so it wont upload it on s3. 

Also there is need to add exception in case of wrong config of file Writer because its very hard to debug without it.

**Comment by mjakubowski84** [comment]
Unfortunately, Hadoop configuration is part of Hadoop. Parquet4s cannot
throw exception in case of mistakes in config because it is not responsible
for connection handling.

śr., 23 paź 2019, 12:42 użytkownik Ajit Kamble <notifications@github.com>
napisał:
