### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by loicdescotte** [mjakubowski84/parquet4s#117]
Would it be possible to compile and publish parquet4s for scala 2.13?

**Comment by mjakubowski84** [comment]
@loicdescotte Yeah, there's a branch with things for planned 1.x  (including support for Scala 2.13). I didn't have time recently to finish it. However, I plan to release it before New Year!

**Comment by mjakubowski84** [comment]
@loicdescotte It is already there!

**Comment by loicdescotte** [comment]
great!
