### ISSUE TITLE
Exposing Flow API

### ISSUE THREAD

**Issue by PavelPenkov** [mjakubowski84/parquet4s#121]
The code required to post-process written records is rather messy (here I'm committing offsets to Kafka):

```
  val committerSink = Flow.fromFunction { msgs: Seq[Message] => CommittableOffsetBatch(msgs.map(_.committableOffset)) }
    .via(Committer.batchFlow(CommitterSettings(system)))
    .toMat(Sink.ignore)(Keep.right)

  val sink = ParquetStreams.toParquetIndefinite[Message, PriceInfo, Future[Done]](
    path = "/user/ppenkov/indef/price",
    maxChunkSize = writeOptions.rowGroupSize,
    chunkWriteTimeWindow = 30 seconds,
    options = writeOptions,
    postWriteSink = committerSink,
    preWriteTransformation = { msg => readFromByteBuffer(msg.record.value) }
  )

```

Are you interested in exposing Flows similar to Alpakka HDFS? If you are, I'll work on a pull request.

**Comment by mjakubowski84** [comment]
Yes, please! Remember to add a feature that closes writers opened by a flow
when stream terminates.

sob., 18 sty 2020, 15:00 użytkownik Pavel Penkov <notifications@github.com>
napisał:

**Comment by PavelPenkov** [comment]
Here's the rough draft version https://gist.github.com/PavelPenkov/afe91a451d62e7c19a0030fb3df72d32
I don't like the code that deals with rotation but it gets the job done. More importantly, it doesn't use `groupedWithin` so it uses way less memory. Is this code good enough for proper PR?

**Comment by mjakubowski84** [comment]
Looks good! Please remember about tests!
