### ISSUE TITLE
Pass non-default Options to reader method

### ISSUE THREAD

**Issue by alexklibisz** [mjakubowski84/parquet4s#125]
Is there a reason that the reader method doesn't take options as a parameter?

https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/ParquetReader.scala#L76

Any alternative way to get a lazy iterable with custom options? Specifically interested in a custom hadoop configuration.

**Comment by mjakubowski84** [comment]
Hi Alex! You pass Options in read function which is a member of Reader.

śr., 1 kwi 2020, 21:38 użytkownik Alex Klibisz <notifications@github.com>
napisał:

**Comment by alexklibisz** [comment]
Ah, got it. Thanks!
