### ISSUE TITLE
Writing Generic Types

### ISSUE THREAD

**Issue by JanNoszczyk** [mjakubowski84/parquet4s#127]
Due to my project requirements, I need to be able to store a list of a generic type in a parquet file. I was wondering whether this is actually achievable with the parquet4s library. Essentially, I want to be able to do this:
`  def savePartitionErrors[R](failedRows: List[(String, R)]): Unit = {
    ParquetWriter.writeAndClose[(String, R)](outputFilePath, failedRows)
  }`
However, this is throwing me an error:
`could not find implicit value for parameter writerFactory: com.github.mjakubowski84.parquet4s.ParquetWriter.ParquetWriterFactory[(String, R)]`
I also tried defining custom encoders and schema definitions as you showed in your examples, but I was still getting the same error, 
I would much appreciate any help with that, thank you in advance!

**Comment by mjakubowski84** [comment]
Hi, sorry for a late response, I missed your issue.

As the error says, you forgot to define implicit `ParquetWriterFactory` in your `savePartitionErrors` function.  Just make it: ```def savePartitionErrors[R: ParquetWriterFactory](...``` and it should already work.  (ParquetWriterFactory finds you a schema and an encoder )
Note that you are using Tuple and field names of tuple are `_1` and `_2` so you may want to use some generic case class to give them a better name. But then you have to define your own encoder and schema.
