### ISSUE TITLE
Split ValueCodec into Encode and Decode traits

### ISSUE THREAD

**Issue by AlecZorab** [mjakubowski84/parquet4s#130]
Hi,

This is possibly out of scope for your project, but I've got a use case where I'm trying to encode java types that I don't control,  based on a schema that I get delivered at runtime. The majority of the project is very well suited to this, even though it's not really what you intended. 

The only difficulty is caused by ValueCodec being invariant in its type parameter

If codec were factored like this:
```
  trait ValueDecoder[+T] {
    def decode(value: Value, configuration: ValueCodecConfiguration): T
  }
  
  trait ValueEncoder[-T] {
    def encode(data: T, configuration: ValueCodecConfiguration): Value
  }

  trait ValueCodec[T] extends ValueEncoder[T] with ValueDecoder[T]
```

It would solve my immediate problem without needing `asInstanceOf` 😁 

More generally, it would allow users to write lossy encoders, eg `ValueEncoder[(Int with Tag[A]) :*: (Int with Tag[B]) :*: HNil ]`, which could be useful in some circumstances.

If this would be a welcome change I can take a look at implementing it - I haven't looked too hard, but I don't think it'll be too difficult.

**Comment by AlecZorab** [comment]
After further thought, I'm not sure that this has much application outside my very specialised use case. I'd still be happy to implement it if you felt it was useful, but I'll close the ticket for now.

**Comment by mjakubowski84** [comment]
Hi Alec!

Thanks for your interest in the project.
Regarding the codecs - in the beginning I kept encoders and decoders
separately but as the project grew it started to be hard to maintain. So I
put them together to keep it simple.
At this moment this project has already quite many users. I believe that
some have their custom codecs. I am afraid that such change may make their
code incompatible with a new version. I would like to avoid that.
I cannot think of any other quick solution for you at this time, sorry.



śr., 22 kwi 2020 o 19:38 Alec Zorab <notifications@github.com> napisał(a):
