### ISSUE TITLE
Avro-unfriendly schema name

### ISSUE THREAD

**Issue by mac01021** [mjakubowski84/parquet4s#131]
This is not your bug, but is easily fixed on your end.

To reproduce:

1. Write some parquet using `parquet4s` to file `sample.snappy.parquet`
2. Try to read it using the following non-parquet4s code:

        AvroParquetReader<GenericRecord> rdr = new AvroParquetReader<>(conf, new Path("sample.snappy.parquet"));
        rdr.read();

3. Behold the resulting exception:  `org.apache.avro.SchemaParseException: Illegal character in: parquet4s-schema`

**Comment by mjakubowski84** [comment]
Feel free to propose another spelling for the scale, e.g.: `Parquet4sSchema`. I guess that Avro tries to create a variable using schema name and `-` is an offender.

**Comment by mac01021** [comment]
Changing the `-` to `_` would do it.  Or removing it altogether.

If it were all up to me, I'd probably just go with the underscore.

**Comment by mjakubowski84** [comment]
So let's go with underscore 👍

**Comment by mjakubowski84** [comment]
Please check if a new schema name works for you #136

**Comment by mac01021** [comment]
I am not at my computer to test right now, but I think that will work
fine.  I can test it when I get home tonight if you don't merge it before
then.

**Comment by marcinaylien** [comment]
no rush!

**Comment by mjakubowski84** [comment]
Released in 1.1.0
