### ISSUE TITLE
Automatically discoverable Encoder/Decoder instances for ParquetRecord

### ISSUE THREAD

**Issue by mac01021** [mjakubowski84/parquet4s#137]
This is not at all important, but might be nice.

I'm actually just creating this issue to congratulate you!

On my naive benchmark, where I 
 - take my company's 8.6 MB parquet file
 - open a reader
 - write each row out, unmodified, to a new file

parquet4s is 30% faster than `AvroParquetReader`+`AvroParquetWriter`.

**Comment by mac01021** [comment]
Using `GenericRecord`, of course.

**Comment by marcinaylien** [comment]
cool! when I will have some more time I will add a description to PR to thank you, too :)

**Comment by mac01021** [comment]
Not necessary!

**Comment by mjakubowski84** [comment]
But I agree, implicit encoder, decoder and schema resolver for ParquetRecord + example would be cool!
