### ISSUE TITLE
Read support for old-style lists.

### ISSUE THREAD

**Issue by mac01021** [mjakubowski84/parquet4s#142]
I'm trying to read some parquet files which don't use the "new" standard encoding of lists:

The schema is like this
```
...
 required group addresses (LIST) {
    repeated group array {
      optional binary street (UTF8);
      optional binary city (UTF8);
      optional binary state (UTF8);
      optional binary country (UTF8);
    }
  }
...
```

I think the thing to do is add another case in `createConverter`, but I'm having trouble figuring it out.  Any pointers are appreciated.

**Comment by mac01021** [comment]
When I try reading this file, each RowParquetRecord comes out like

```
...
(addresses,ListParquetRecord (NullValue,NullValue,NullValue,NullValue))
...
```

rather than a list of RowParquetRecords.

**Comment by mjakubowski84** [comment]
Hi again! Your issue (NullValues) come from here: ```https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/ParquetRecord.scala#L228```.
That means that the repeated group name (`array`) is other than expected (`element`).
I could have done a wrong assumption about the names of list elements. What would you say about changing that `get(ElementFieldName)` here by `head` in order to make it more generic?

**Comment by mac01021** [comment]
Interesting.  I'm not sure it's precisely that simple to fix because the standard list encoding (which you already handle perfectly) has three levels of schema
```
[optional | required] group my_list_field (LIST) {
     repeated group list {
        [optional | required] group element {
              <... fields ...>
        }
     }
}
```

while my stupid old parquet files have only two levels of schema

```
[optional | required] group my_list_field (LIST) {
     repeated group array {
          <... fields ...>
     }
}
```

**Comment by mac01021** [comment]
This (https://github.com/apache/parquet-format/pull/17/files) talks all about encoding lists and maps in parquet.  The standard is supposed to work exactly the way Parquet4s is currently reading it.

But there are various forms that readers are supposed to honor for backward compatibility.

One is the example i give above in this issue.  Another is the occurrence of a `repeated` field type where no containing group is annotated with the `LIST` original type.

**Comment by mjakubowski84** [comment]
You're right. That is more complex. I focused on compatibility with documents produced by Spark (that was my only requirement for the project when I created it). 
The case you shared is still easy to handle inside ListParquetRecord (e.g. if added value is `RowParquetRecord` but has no field with name `ElementFieldName` then add the whole record as an element). 
Some other cases still seem to be easy to handle. More fun is with repeated records which are not encapsulated by a `LIST` group. I am not sure if they are still supported by Parquet at all (I had some problems with that in the past).

**Comment by mac01021** [comment]
That would be the quick and easy solution.  And if it were some how magically released in the next 12 hours it would save me a bunch of work.

If you want a "full" solution that doesn't break if the `array` group happens to have a field called `element` among its others, it would still require a bigger change, as for the unencapsulated repeated records.

**Comment by mjakubowski84** [comment]
I'm away from the computer. If you can handle this change on your own so
that it suits you (including tests) then I can release it as a bugfix
version later in the evening (CEST time).

wt., 16 cze 2020, 17:37 użytkownik Matthew Coolbeth <
notifications@github.com> napisał:

**Comment by mjakubowski84** [comment]
I refactored tests a little bit so they use more of ScalaTest flavour. Release is on the go.

**Comment by mac01021** [comment]
Thank you!  I apologize for my lack of familiarity with ScalaTest.

**Comment by mac01021** [comment]
It looks like maybe. the release failed?

**Comment by marcinaylien** [comment]
GatewayTimeout in Sonatype - retrying

**Comment by mjakubowski84** [comment]
Argh... actually it got released... There was no need for retries. Please check and give me a shout if smth is wrong.

**Comment by mac01021** [comment]
It works!  Thanks for all the help!
