### ISSUE TITLE
example for non case class read

### ISSUE THREAD

**Issue by lake4790k** [mjakubowski84/parquet4s#145]
This is an awesome library. Could you provide a little example for reading without case classes for speed?

**Comment by marcinaylien** [comment]
Thanks! It is already there: https://github.com/mjakubowski84/parquet4s/blob/master/examples/src/main/scala/com/github/mjakubowski84/parquet4s/core/WriteAndReadGenericApp.scala

**Comment by lake4790k** [comment]
fantastic thank you!
