### ISSUE TITLE
Allow for monitoring the internal row counter

### ISSUE THREAD

**Issue by dkwi** [mjakubowski84/parquet4s#171]
This is a really great library because it's so simple and easy to use. But I found one small thing to be missing. 
I would like to have a quick discussion about whether it's needed and about possible solutions, before I'll create a pull request.

Inside `ParquetPartitioningFlow` there's a variable called `count`. 
It would be very useful if it was externalised in some way (for better monitoring, logging or just custom logic based on the internal cache).

I was thinking of a couple of ways to implement this:
1. Simply adding a handler to the `viaParquet` builder. something like: 
```
def withBatchSizeHandler( handler :Int=>Boolean )
```
Where `Int` is the batch size, and `Boolean` is whether a flush should be forced.

2. Emitting `(T, MetaData)` instead of `T` from the FlowShape, where `MetaData` can be all the internal metadata, including the counter and a manual flush function.
Then it would be used like this:
```
...
.via(parquetFlow)
.via(Flow[(T,MetaData)].map { case (t, md) =>   if (doStuff(md.count)) md.flush() .... }            
...
```

Thanks

**Comment by mjakubowski84** [comment]
Hi!

I would like to not change the API of the flow. Changing the emitted value would be a breaking change in quite a high extend.
Could you please explain in more details what is your use case? Cannot it be achieved by parameters that are already there? Because flushing on reaching given count is already there (check `maxCount` parameter).

If there's something more then I recommend creating a meterialized value for `ParquetPartitioningFlow` by extending `GraphStageWithMaterializedValue` instead of `GraphStage`. It will allow to interact with with the flow.

Another possibility - causing even less changes in the API is to add to config builder some kind of listeners... what actually is more or less what you suggested in the first option. But maybe current `count` is too little for other users. We may think of some kind of context, currently processed message, etc.

**Comment by dkwi** [comment]
> I would like to not change the API of the flow. Changing the emitted value would be a breaking change in quite a high extend.

>If there's something more then I recommend creating a meterialized value for ParquetPartitioningFlow by extending GraphStageWithMaterializedValue instead of GraphStage. It will allow to interact with with the flow.

You're right. A materiazlied value is a better. 

>Could you please explain in more details what is your use case? Cannot it be achieved by parameters that are already there?
I have 2 goals: 
1. I would like to monitor the size of the batch. This way I would be able to tune a better balance between `maxCount` and `maxDuration`.
2. I would also like to have certain conditions under which the batch is flushed - without reaching `maxCount` or `MaxDuration`.


>Another possibility - causing even less changes in the API is to add to config builder some kind of listeners... 

I think this is probably the best option, since it's the least intrusive and would not change any type signatures.
What did you have in mind for a context? 
I guess `count` and the `Map` of writers could be useful.
Also, when would it be best to invoke this/these listeners ? on push ?

**Comment by mjakubowski84** [comment]
Yeah, listener seems to be the best option. It can be invoked just after the write.

**Comment by mjakubowski84** [comment]
Thanks for contributing!
I merged the PR but before the release I would like to add the same feature to FS2 module for consistency. Would you like to take care of it or do you prefer to wait till end of week for me?

**Comment by dkwi** [comment]
I'm not as familiar with FS2, but I would like to give it a try today.

**Comment by dkwi** [comment]
I've tried to add it today, but something isn't working right... As I've said, I'm not very familiar with FS2.
I'll give it another try on the weekend, unless you would like to do it.

**Comment by mjakubowski84** [comment]
Hi again. Sorry for not responding. I didn't know if I will find a time to have a look at this. Today I have and I will add FS2 support.

**Comment by dkwi** [comment]
Cool, thanks!

**Comment by mjakubowski84** [comment]
@dkwi Released!
I took advantage of this new function to test error handling in streams. Found a bug and fixed it!

**Comment by dkwi** [comment]
Wow! amazing!
