### ISSUE TITLE
Reading a parquet file as array of bytes

### ISSUE THREAD

**Issue by oshyshkin** [mjakubowski84/parquet4s#175]
Hi everyone. Thank you for the amazing project. I try to use it in my data processing pipeline (on AWS).
But I cannot use S3 path to read data, and I would like to do something like here (use an array of bytes instead of a path):
https://stackoverflow.com/questions/58141248/read-parquet-data-from-bytearrayoutputstream-instead-of-file

The problem is that I cannot really use Hadoop configuration to grant access to S3 (at least I didn't succeed) and I do need to use array of bytes instead of a path. Here is a little bit of context and details.

I have a service on EC2 and the service needs to read a parquet file, convert it to a list of some records (custom case class) and do some data manipulation. Also, we wrap the code into Spark UDF (so we can run the same code for our service and Spark job).

**The first try**
I cannot hardcode AWS keys into the code so I used the next thing:
```
import org.apache.hadoop.conf.Configuration
import com.amazonaws.auth.DefaultAWSCredentialsProviderChain

val config = new Configuration()
val chain = new DefaultAWSCredentialsProviderChain()
val creds = chain.getCredentials
config.set("fs.s3.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
config.set("fs.s3.awsAccessKeyId", creds.getAWSAccessKeyId)
config.set("fs.s3.awsSecretAccessKey", creds.getAWSSecretKey)
```

It does work well if you have `~/.aws/credentials` file. But on EC2 we use AWS policy to grant S3 access etc. I cannot change it or add `~/.aws/credentials` file, so the option doesn't work for me.

**The second try**
As I don't really need to read the file really othen and it is not big, so I decided to write it on local disk and then read the file from there. It looks like this:
```
val referenceTableKey = getFirstS3KeyByPrefix(bucket, prefix)
val referenceData = fetchS3Object(bucket, referenceTableKey)
val path = "./tmp.parquet"
val bos = new BufferedOutputStream(new FileOutputStream(path))
bos.write(referenceData)
bos.close()
val records = ParquetReader
  .withProjection[MyCustomClass]
  .read(path)
  .toList
```

I use AWS SDK for reading data from S3 so there is no problems with permissions, so in general it works well and does what I need. But not when I need to run a Spark job using UDF.

**A problem with UDF**
When I run Spark I get the next error:
``` File hdfs://172.22.11.33:8020/user/hadoop/tmp.parquet does not exist.```

Looks like it goes to HDFS instead of using OS file system when it runs under Spark session. I don't really understand what is the next step or how I can recofigure it. Therefore, I see only 2 options:
1. Write data on HDFS somehow. But it requires code changes in my service and it doesn't look really good to me.
2. Read data while it is in memory.

I'm not sure how I can implement the second option. I guess it needs to be implemented on parquet4s side (adding another read method or something). Any ideas? Do I miss other options? 
Any help is appreciated. Thanks!

**Comment by mjakubowski84** [comment]
Hi @oshyshkin,

Please read documentation of Hadoop Client for AWS. Quick example how to setup credentials and a link do documentation of Hadoop Client is in Readme.
