### ISSUE TITLE
Question for scala3 

### ISSUE THREAD

**Issue by Swoorup** [mjakubowski84/parquet4s#176]
Any ideas if its possible to get this working for scala3. I don't have much prior experience with scala. But have been testing Scala 3.0.0-M3 for the past month. Wondering if its possible to get this working with scala3 using a workaround?

Using the akka-stream example, I get build issues:

```
no implicit argument of type com.github.mjakubowski84.parquet4s.PartitionLens[finflow.io.storage.OrderRecord] was found for parameter partitionLens of method build in trait Builder.
I found:

    com.github.mjakubowski84.parquet4s.PartitionLens.genericLens[T, R](
      shapeless.LabelledGeneric.materializeProduct[T, K, V, R](
        shapeless.~?>.witness[Nothing, Nothing, T](
          shapeless.~?>.rel[Nothing, Nothing]
        )
      , ???, ???, ???)
    , ???)

But method witness in trait NatTRel0 does not match type shapeless.DefaultSymbolicLabelling.Aux[T, K].
```

**Comment by mjakubowski84** [comment]
Hi!

Scala 3 has not been fully released yet and so are other Scala libraries
dedicated for it. Parquet4s depands on Shapeless - version for Scala3 is in
early preview and I even cannot find it in Maven Central:
https://github.com/milessabin/shapeless/releases/tag/v3.0.0-M1


czw., 31 gru 2020, 16:50 użytkownik Swoorup Joshi <notifications@github.com>
napisał:
