### ISSUE TITLE
parquet split files ordering

### ISSUE THREAD

**Issue by Swoorup** [mjakubowski84/parquet4s#178]
Is there a way to have ordered reads when consuming parquet multiple split files?
My folder has files such as 

```
.29a348b3-551e-488a-94b7-d808b974db6e.gz.parquet.crc
.177e4cd4-a8c5-4c51-997f-a9e62fe95d2c.gz.parquet.crc
.180fe2f3-ce02-47a0-bf52-d43375ee80d0.gz.parquet.crc
.d0f4eeb3-5000-4e72-9494-2b83484c4e59.gz.parquet.crc
8aa11d3a-c817-40a7-a5b7-1967d5749339.gz.parquet
29a348b3-551e-488a-94b7-d808b974db6e.gz.parquet
177e4cd4-a8c5-4c51-997f-a9e62fe95d2c.gz.parquet
180fe2f3-ce02-47a0-bf52-d43375ee80d0.gz.parquet
```

which was written using 
```scala
  val writeOptions = ParquetWriter.Options(
    writeMode = ParquetFileWriter.Mode.OVERWRITE,
    compressionCodecName = CompressionCodecName.GZIP,
    dictionaryEncodingEnabled = true
  )

  def getReadSource(filePath: String) = 
    ParquetStreams.fromParquet[OrderRecord]
      .withOptions(ParquetReader.Options())
      .read(filePath)

  def getWriteFlow(filePath: String) = 
    ParquetStreams
      .viaParquet[OrderRecord](filePath)
      .withMaxCount(writeOptions.rowGroupSize)
      // .withMaxDuration(10.seconds)
      .withMaxDuration(1.hour)
      .withWriteOptions(writeOptions)
      .build()
```

It appears when consuming it back via getReadSource, the ordering appears to be off?

**Comment by mjakubowski84** [comment]
AFAIR Hadoop client reads files according to file system ordering. If you want to keep order of your files as they are created then please keep your directory sorted by file creation time (which is usually a default one in most of fs).

**Comment by Swoorup** [comment]
That seems bit odd to rely on file system. I did enable sort by creation time in finder(macOS), but still the ordering appears to be off?

**Comment by mjakubowski84** [comment]
Hi! Sorry for a late response.

I don't fully agree that relying on the file system is odd. What else could give you a list of files in a directory if not a file system. True, some extra ordering can be added afterwards but Parquet doesn't do it:
https://github.com/apache/parquet-mr/blob/master/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetReader.java#L347
So, the order of files read depends on HDFS (or other underlying file system).
