### ISSUE TITLE
How to use parquet4s-core together with BrotliCodec

### ISSUE THREAD

**Issue by tmichniewski** [mjakubowski84/parquet4s#179]
Hello,
Do you have some example of reading parquet file with parquet4s-core library when parquet file is compressed using let say BrotliCodec?
Best wishes,
Tomek

**Comment by mjakubowski84** [comment]
Hi!

I don’t have any example but there shouldn’t be anything special for you to do except adding this to your classpath: https://github.com/rdblue/brotli-codec/blob/master/src/main/java/org/apache/hadoop/io/compress/BrotliCodec.java <https://github.com/rdblue/brotli-codec/blob/master/src/main/java/org/apache/hadoop/io/compress/BrotliCodec.java>. Parquet should recognise the compression codec automatically.

Cheers,
Marcin

**Comment by mjakubowski84** [comment]
Hi @tmichniewski! Did you solve your problem? Can we close the issue?

**Comment by tmichniewski** [comment]
Hello,

Well, it was not enough to add the BrotliCodec dependency to built.sbt, because a few more classes were missing.
On the contrary adding this to built.sbt was enough when using with Spark.

This was at the exact moment when we decided not to experiment directly with parquets and rely on Spark instead.

Yes, you can close this ticket, as it is no more important.

Best wishes,
Tomek
