### ISSUE TITLE
Cannot import parquet4s in ammonite-repl

### ISSUE THREAD

**Issue by ankusharya** [mjakubowski84/parquet4s#180]
Facing issue in ivy import for parquet4s

**Ammonite-repl version**: Ammonite REPL & Script-Runner, 2.3.8
**Java Version**: openjdk version "1.8.0_275"

**Ammonite-repl script**:
@ import $ivy.\`com.github.mjakubowski84::parquet4s:0.1.0\`

**Error**
Failed to resolve ivy dependencies:Error downloading com.github.mjakubowski84:parquet4s_2.13:0.1.0
  not found: /Users/ankushs/.ivy2/local/com.github.mjakubowski84/parquet4s_2.13/0.1.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/github/mjakubowski84/parquet4s_2.13/0.1.0/parquet4s_2.13-0.1.0.pom

**Comment by mjakubowski84** [comment]
Hi!
You're using the very first version of the library which was never released for Scala 2.13. Check Readme and examples for how to use newer versions which supports it.
