### ISSUE TITLE
Exception while serialize a case class in Scala

### ISSUE THREAD

**Issue by ZviMints** [mjakubowski84/parquet4s#181]
I have the following class:
```

class ParquetService extends LazyLogging {

  private final val PARQUET_SUFFIX = "parquet"

  def write[T](list: Iterable[T],
               key: String)(implicit writerFactory: ParquetWriterFactory[T]): String = {
    val path = File.createTempFile(s"$key-", s".$PARQUET_SUFFIX").getAbsolutePath
    ParquetWriter.writeAndClose(
      path,
      list,
      ParquetWriter.Options(
        writeMode = ParquetFileWriter.Mode.OVERWRITE,
        compressionCodecName = CompressionCodecName.SNAPPY))
    path
  }
}
```
and following test:
```
"ParquetService" - {
    "write" in {
      val n = 10000
      val events = generators.EventGen.listOfN(n).arbitrary.sample.get
      val path = service.write(events, "recordId/assets")
      val file = new File(path)
      println(path)
    }
}
```
when `Event` is:
```
case class Event(recordingId: String,
                 awsMessageId: String,
                 pacificEvent: PacificEvent,
                 eType: EventType,
                 data: Option[JsObject],
                 createdAt: Instant,
                 errors: List[String],
                 status: EventStatus)
```
And i having the following exception:
```
Error:(52, 31) could not find implicit value for parameter writerFactory: com.github.mjakubowski84.parquet4s.ParquetWriter.ParquetWriterFactory[com.bluedot.thomas.model.Event]
      val path = service.write(events, "recordId/assets")
```
Any ideas how to solve it?
Its also fails instead of events with list of integers - `List(1,2,3)`

versions:
```
  val parquet4s = Seq(
    "com.github.mjakubowski84" %% "parquet4s-core" % "1.7.0"
  )
```

**Comment by ZviMints** [comment]
Hey @mjakubowski84, I can make some mapper for `JsObject` to `JsString(Json.stringify(Json.toJson(element)))` which should work.
Thanks

**Comment by mjakubowski84** [comment]
it rather is a parquet file :)
regarding your read function - you close it before you read it, remember that Iterable in Scala is lazy

**Comment by ZviMints** [comment]
@mjakubowski84 
Its shows me the file as a Generic Document, I can see it when i upload it to S3 as follows:
```def uploadFile(recordingId: String, key: String, path: String): Future[MultipartUploadResult] = {
    FileIO.fromPath(Paths.get(path))
      .log(s"[S3Service] - Stream for request uploadFile($recordingId, $key, $path path)")
      .withAttributes(Attributes.logLevels(onFailure = LogLevels.Error, onFinish = LogLevels.Info, onElement = LogLevels.Off))
      .via(Compression.gzip)
      .runWith(S3.multipartUpload(s"$THOMAS_BUCKET", s"$recordingId/$key"))
  }
```
The path is what returned from the old function, I see it in S3 as follows:
![image](https://user-images.githubusercontent.com/43406781/110520410-19157680-8117-11eb-80cf-7440cbbbf05e.png)

Without any `.parquet` suffix

2. What do you mean? I would like for some suggestings for my writes/reads from the owner :)

Thanks @mjakubowski84 !!! :)

**Comment by mjakubowski84** [comment]
1. I am not sure if there is smth wrong with the file. I only see that size is small. You can use parquet-tools locally to examine it (`brew info parquet-tools`). You can also use reader of Parquet4S to check what you wrote.
2. You close iterators before files is read. According to the code you shared:
```
    parquetIterable.close()
    parquetIterable.toList
```
It should be otherwise.
3. There's no need to use AWS SDK to download or uploads files from/to S3. Parquet does it for (you check Readme of Parquet4S and docs of hadoop-aws). Parquet4S also has Alpakka-like integration for Akka Streams.
4. Compression in Parquet is done internally on rowgroup and column level. You can't just treat Parquet file as a plain file that gets compressed. And there's no need to uncompress files on your own. Parquet does it for you.

**Comment by ZviMints** [comment]
I changed read to:
```
def read[T](path: String)(implicit reader: ParquetReader[T]): List[T] = {
    val parquetIterable = ParquetReader.read[T](path)
    val res = parquetIterable.toList
    parquetIterable.close()
    res
  }
```
I guess this what you meant.
Thanks @mjakubowski84 , was very helpful.
