### ISSUE TITLE
error: could not find implicit value for parameter writerFactory

### ISSUE THREAD

**Issue by ag4s** [mjakubowski84/parquet4s#182]
Below is my case class, 
`case class Type(
				code: String,
				description: String,
				any: Seq[scalaxb.DataRecord[Any]] = Nil)`
`case class Types(
				type: Seq[Type] = Nil,
				attributes: Map[String, scalaxb.DataRecord[Any]] = Map.empty) {
                                lazy val typeValue = attributes("@type").as[String]}`
`case class Rdic(
					types: Seq[types] = Nil,
				        any: Seq[scalaxb.DataRecord[Any]] = Nil)
`
I assign all the values in a val (fromFile) and tried to use that val to create the parquet file using the below code 
ParquetWriter.writeAndClose(path, fromFile) 

I am getting the below error 

_error: could not find implicit value for parameter writerFactory: com.github.mjakubowski84.parquet4s.ParquetWriter.ParquetWriterFactory[Rdic]
Error occurred in an application involving default arguments._

I tried to define val as implicit still getting the same issue

**Comment by mjakubowski84** [comment]
Hi @ag4s!
You're using `scalaxb.DataRecord[Any]` type that is not recognised by Parquet4s. it just doesn't know how to de/serialise it. Please refer to the documentation to know what kind of types are supported out of the box and how to define your custom codecs.

**Comment by ag4s** [comment]
ok thanks for reply.. will custom codecs work in this case? if so, how should I build it? basically I am reading XML file in case class and want to save it to parquet. Is any option available?

**Comment by marcinaylien** [comment]
Yes, they should work. Please refer to the documentation and examples.

**Comment by ag4s** [comment]
ok, I am working on it currently. I will keep you updated

**Comment by ag4s** [comment]
I tried to generate codecs by myself but not getting success. An example in the documentation is too simple to implement. Can you give an idea of how the codecs for the above will be? Then, taking that as a reference I will generate the remaining ones.

**Comment by marcinaylien** [comment]
I am not very familiar with Scalaxb and the schema of your xml files. I don't know what you really want to save. But I see several options that you can consider to ease your life:
1. Avoid using `Any`, try to map the schema to some more specific types using scalaxb.
2. Before running parquet4s transform the data to different model using basic Scala collections and your own domain case classes so that you do not have to write complex codecs for mapping the whole family of scalaxb types. For example you may want to turn `Seq[DataRecord[Any]]` into `Map[String, Any]` or `Map[String, YourType]`.
3. Use pattern matching in codec for mapping the scalaxb types:

```
implicit val scalaxbCodec: OptionalValueCodec[DataRecord[Any]] = 
  new OptionalValueCodec[CustomType] {
    override protected def decodeNonNull(value: Value, configuration: ValueCodecConfiguration): DataRecord[Any] = ???
    override protected def encodeNonNull(data: DataRecord[Any], configuration: ValueCodecConfiguration): Value = {
      data match {
         case DataRecord(uri, key, Some(value: Int)) => implicitly[ValueCodec[Int]].encode(value, configuration)
         // more mappings
      }
    }
}
```

**Comment by ag4s** [comment]
Thanks appreciate that, I am currently working on it

**Comment by ag4s** [comment]
Didn't work for simple case classes also. Getting the same issue for that case class.

**Comment by ag4s** [comment]
simplified case class now, Not using DataRecord[Any] at all. Now getting the following error

```
case class Sou(
                       id: String,
                       url: Option[Option[String]] = None,)

case class Sou_updates(source_item: Seq[Sou] = Nil)

case class Sources(Sou_updates: Option[Sou_updates] = None)
```

```
org.apache.hadoop.fs.FileAlreadyExistsException: File already exists: file:/C:/Users/AshishGaikwad/RDC/parquet
  at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:313)
  at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:351)
  at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSOutputSummer.<init>(ChecksumFileSystem.java:401)
  at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:464)
  at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:443)
  at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1118)
  at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1098)
  at org.apache.parquet.hadoop.util.HadoopOutputFile.create(HadoopOutputFile.java:74)
  at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:295)
  at org.apache.parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:283)
  at org.apache.parquet.hadoop.ParquetWriter$Builder.build(ParquetWriter.java:569)
  at com.github.mjakubowski84.parquet4s.ParquetWriter$.internalWriter(ParquetWriter.scala:95)
  at com.github.mjakubowski84.parquet4s.DefaultParquetWriter.<init>(ParquetWriter.scala:136)
  at com.github.mjakubowski84.parquet4s.ParquetWriter$.$anonfun$writerFactory$1(ParquetWriter.scala:125)
  at com.github.mjakubowski84.parquet4s.ParquetWriter$.writeAndClose(ParquetWriter.scala:111)
  ... 28 elided
```

**Comment by mjakubowski84** [comment]
I think that the exception is self-explanatory :) You can change the write options to override the file.
BTW take a look at `Option[Option[String]] = None` :)

**Comment by ag4s** [comment]
Sorry for not being clear, the folder is empty and it gives the same error. No file is getting created in the first place itself.   I suspect some other issue is causing it.Thanks corrected `Option[Option[String]] = None` to `Option[String] = None` :)

**Comment by mjakubowski84** [comment]
ParquetWriter in core nodule creates a single file with the provided name. So if you have a directory called `C:/Users/AshishGaikwad/RDC/parquet` then it already exists.

**Comment by ag4s** [comment]
Thanks sorted :) ... can you please remove the C;/ directory path
