### ISSUE TITLE
Support list from Spark Parquet legacy format 

### ISSUE THREAD

**Issue by malonsocasas** [mjakubowski84/parquet4s#184]
Hello here !

I'm using parquet4s in a context where parquet files are written by Spark with parquet legacy format activated (mainly for Athena v1 compatibility). I'm having an issue when reading columns of type `Seq[String]`.

The parquet list format used by Spark is the following:
```
<list-repetition> group <name> (LIST) {
   optional group bag {
     repeated <element-type> array;
   }
} 
```
As seen here https://github.com/apache/spark/blob/v3.1.1/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaConverter.scala#L455

This format is currently not handled by parquet4s. This is the error I get:
`Caused by: scala.MatchError: RowParquetRecord (array=BinaryValue(Binary{4 constant bytes, [121, 101, 97, 114]})) (of class com.github.mjakubowski84.parquet4s.RowParquetRecord)`

As I understand, the repeated element should currently be named `element` :
https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/ParquetRecord.scala#L365

Would it be possible to handle repeated elements named `array` ?

Thanks for your help !

**Comment by mjakubowski84** [comment]
Hi!
Sure, we can add support for reading this legacy format. Feel free to create a PR to match also legacy 'array' element. As you say that should be enough to make it working for you.

**Comment by malonsocasas** [comment]
Great ! I create the PR then

**Comment by mjakubowski84** [comment]
@malonsocasas Your fix is released: https://github.com/mjakubowski84/parquet4s/releases/tag/v1.8.1

**Comment by malonsocasas** [comment]
That was fast, thanks a lot ! :)
