### ISSUE TITLE
[akka] Files not rotated when maxDuration is reached

### ISSUE THREAD

**Issue by sndnv** [mjakubowski84/parquet4s#219]
Basically, the akka-stream file rotation does not work as I would expect it, unless there is a constant stream of data.

[This](https://github.com/mjakubowski84/parquet4s/blob/master/akka/src/main/scala/com/github/mjakubowski84/parquet4s/ParquetPartitioningFlow.scala#L211) is the relevant piece of code; the `shouldRotate` flag is set when the timer triggers but the actual rotation is only done when `onPush` is called [here](https://github.com/mjakubowski84/parquet4s/blob/master/akka/src/main/scala/com/github/mjakubowski84/parquet4s/ParquetPartitioningFlow.scala#L216).

I found issue this during some testing where messages were pushed but the `maxCount` was never reached; my expectation was that after the configured `maxDuration` was reached (5 minutes in my case), the files will be written anyway but nothing showed up on S3. Pushing some more data (still well under the `maxCount` value) caused the files to be immediately written.

What I'm not sure about is whether this was intentional, so some feedback will be welcome =]

**Comment by mjakubowski84** [comment]
Thanks!
I will make a bugfix release today in a a free time.

**Comment by sndnv** [comment]
Great, thanks!

**Comment by mjakubowski84** [comment]
It is released! Sorry for the delay.
