### ISSUE TITLE
How to use implicit ParquetSchemaResolver in 1.9?

### ISSUE THREAD

**Issue by JiajunBernoulli** [mjakubowski84/parquet4s#235]
Hello, I am a beginner of scala. I want to read with projection.
case class is is convenient, but not universal enough.
```ParquetReader
  .withProjection[Data] // I need to read many different schema, so I can't create case class for every one.
  .read(
    path = "path/to/file", 
    options = ParquetReader.Options(), 
    filter = Col("id") > 100
  )
```
I can't find any examples about `implicit ParquetSchemaResolver`, do you have any examples？

**Comment by JiajunBernoulli** [comment]
I've found a way
```
//    implicit val partialSchema: MessageType = ParquetSchemaResolver.resolveSchema[User]
val fileds = List(
  Types.primitive(BINARY, OPTIONAL).as(StringType).named("name"),
  Types.primitive(BINARY, OPTIONAL).as(StringType).named("userId"))
implicit val schema = Message(
Some("org.nefu.parquet4s.User"),
  fileds:_*)
val parquetIterable = ParquetReader.withProjection[RowParquetRecord].read(path)
```

**Comment by mjakubowski84** [comment]
There's a example in branch 1.9 for that: https://github.com/mjakubowski84/parquet4s/blob/1.9/examples/src/main/scala/com/github/mjakubowski84/parquet4s/core/WriteAndReadGenericApp.scala

However, I recommend to move to version 2.x. Reading is even more fast. And soon (PR is already there), reading files in a generic way will be even more easy.
