### ISSUE TITLE
how to save empty List[Map[String, Any]] to parquet file with schema

### ISSUE THREAD

**Issue by fywxin** [mjakubowski84/parquet4s#238]

**Comment by mjakubowski84** [comment]
The issue is `Any`. Any has no schema, because it is any type :)
Either to do not use Any but a concrete type. Or write a custom encoder for handling all possible cases. Refer to docs to check how to do it.

**Comment by fywxin** [comment]
> The issue is `Any`. Any has no schema, because it is any type :) Either to do not use Any but a concrete type. Or write a custom encoder for handling all possible cases. Refer to docs to check how to do it.

thank mjakubowski84！ I have resolved this problem～
