### ISSUE TITLE
partitionBy to do not include partition key into filesystem path

### ISSUE THREAD

**Issue by s1rc0** [mjakubowski84/parquet4s#240]
Hi,

I use parquet4s with Akka Streams. Lib allows you to partition data via `partitionBy()` method.
Any way to do not include specified partition key into path name?

In example if I have `.partitionBy(Col("name"))` parquet4s will create folder `name=nameFromMyData`.
Is it possible to have folder with name `nameFromMyData` ?

Thanks in advance

**Comment by mjakubowski84** [comment]
Hi Sergey,
No, it is not possible at the moment to have non-standard partition names. Parquet4s follows the most common standard which allows to restore both the column name and value during reading. However, if you wish to contribute, I think it should be quite easy to create additional optional parameter to builder, e.g. `partitionFormat` where you could use string format for define custom partition format.
