### ISSUE TITLE
Feature request: InputFile and OutputFile support

### ISSUE THREAD

**Issue by nkconnor** [mjakubowski84/parquet4s#249]
Title says it all. I would love to try the library out but think I require `ParquetReader`'s `InputFile` constructor. From looking around, it seems like only `Path` is supported.

**Comment by mjakubowski84** [comment]
Hi @nkconnor. I do not have plans myself atm to introduce `InputFile` as parameter. Feel free to propose a PR.
Hint: probably you can add an alternative build (`read`) function in `Builder` in core and other modules.

**Comment by mjakubowski84** [comment]
@huajiang-tubi here is an issue that is related to your PR

**Comment by mjakubowski84** [comment]
A support for `InputFile` and `OutputFile` is released in https://github.com/mjakubowski84/parquet4s/releases/tag/v2.12.0.
