### ISSUE TITLE
Can I trouble you for code review to integrated newer version of parquet4s into delta DSR/DSW?

### ISSUE THREAD

**Issue by MironAtHome** [mjakubowski84/parquet4s#256]
I am not sure how much effort, just asking if you would be willing and available to look over PR.
It's currently stack at 1.2.1 and it's just too far back. Causes troubles with deps and I really don't like shading if I have to use it as a workaround.

**Comment by mjakubowski84** [comment]
@MironAtHome Sure thing!

**Comment by MironAtHome** [comment]
Most of the changes were to wrap file path expressed as string into .Path imported from latest version of parquet4s parquet implementation.
However, two kinds of errors turned out a bit heavier to mend.
1, ParquetReader.read in CloseableParquetDataIterator.scala:154
2. ValueCodec with root of the trouble in RowParquetRecordImpl.scala:308 and a few lines, related to ValueCodec. I am not certain what to replace those with directly, if such a substitute readily available, please suggest, else, will put together a few lines to wrap new classes and expose same interface

**Comment by mjakubowski84** [comment]
I think that this can be helpful: https://mjakubowski84.github.io/parquet4s/docs/migration/

**Comment by mjakubowski84** [comment]
Regarding `RowParquetRecordImpl`:
 - `ValueCodec`'s implementation is now split into `ValueEncoder` + `ValueDecoder` so here probably you want to use `ValueDecoder.intDecoder`
 - `private def customSeqCodec[T](elementCodec: ValueCodec[T])(implicit` seems to be redundant for me. The comment above the function sounds as not true to me.

**Comment by MironAtHome** [comment]
Great thank you for your guidance and help.
Started from this pr to ensure build.
https://github.com/mjakubowski84/parquet4s/pull/257

**Comment by MironAtHome** [comment]
Hey Marcin, pr is ready
https://github.com/delta-io/connectors/pull/303
please provide feedback

**Comment by mjakubowski84** [comment]
Two comment from me only. One is a minor code change but the other worries me. I see that Delta relies on some ancient version of parquet-hadoop. I wonder if that can be upgraded without any issue.

**Comment by MironAtHome** [comment]
Hey Marcin, sorry for interruption, I had to get over case of covid.
I have ran into an issue with boolean type decode in the connector with edition 2.3.0 ( latest available on maven of parquet4s ).
Could you please look?
I have created a private repo for this unit test.
https://github.com/MironAtHome/connectors-private.git
branch 
miron/integrate-parquet4s-23
here is the lines where I am getting assertion:

          val b: Boolean = (i % 2 == 0)
          val rowB: Boolean = row.getBoolean("as_boolean")
          println(s"Evaluating row value ${rowB} to ${b} for (${i} % 2 == 0)} as ${(i % 2 == 0)}")
          assert(row.getBoolean("as_boolean") == (i % 2 == 0))

when I ran on these rows spark 3.2 with hadoop 3.2 I am getting proper values, however, unit test produces assertion for value rowB compared to value at "as_int" field 0 ( this is integer value used to generate test values in the test table )

**Comment by mjakubowski84** [comment]
Hi @MironAtHome.

I do not see the code as your repo is private.
I recommend to have a look at boolean decoder and debug what happens there. I do not recall if business logic changed there since version 1.0 - probably not.
And BTW - latest version of Parquet4s is now 1.4.1 :)

**Comment by MironAtHome** [comment]
Marcin, it is so nice to have your comments.
I apologies, I knew my repo setup security wasn't right for your access, but I thought that having you invited through issue link might open it up for you.
Give me till EOD ( it's 9:47AM in Seattle right now ) to get to it, or ask you for further assistance. Will open access right now.

**Comment by mjakubowski84** [comment]
I took me time to debug those tests. Thousands of dependencies and buggy resource loading of golden tables.

So, the issue seems to be with the test data or with the test itself.

Tests fail on `NullValue`. `as_boolean` is set to be nullable. In effect here we cast null to Boolean - https://github.com/MironAtHome/connectors-private/blob/miron/integrate-parquet4s-23/standalone/src/main/scala-2.12/io/delta/standalone/internal/data/RowParquetRecordImpl.scala#L167. And null is resolved as false. So if the test expects true then it must fail.

**Comment by mjakubowski84** [comment]
Hi!
Great to hear that.
No, there's no need to have Hadoop on your machine (I don't). And I don't have `HADOOP_HOME` set, too.

**Comment by MironAtHome** [comment]
Here is my stack dump, first with screenshot of debugger stepped into method caused exception:
![image](https://user-images.githubusercontent.com/18360184/201359472-67681335-2d2d-4188-9fdd-0c92ed3ec320.png)

**Comment by MironAtHome** [comment]
Well, a quick look at \parquet4s\core\src\main\scala\com\github\mjakubowski84\parquet4s\ParquetWriter.scala nets this finding: 
![image](https://user-images.githubusercontent.com/18360184/201987112-314f2c13-a2af-4ee3-9e98-99e14263d790.png)
In the end we do need to have hadoop on local. Which is ok.
Unless I miss something really glaring.
Let's see if we can find anything to change this.

**Comment by mjakubowski84** [comment]
TBH, I haven't been using Windows for many, many years, so it is the first time I have seen such an error :)
For sure, you do need local Hadoop when using a Hadoop client on Mac and Linux.
