### ISSUE TITLE
Benefit from recent changes in FilterAPI of parquet-hadoop

### ISSUE THREAD

**Issue by mjakubowski84** [mjakubowski84/parquet4s#272]
Parquet 1.12.3 introduced `In` and `NotIn` filter predicates.
 - Let's replace our own implementation of `in` backed by `UserDefinedPredicate`

**Comment by saucam** [comment]
@mjakubowski84 I would like to try this one!

**Comment by saucam** [comment]
Thank you! @mjakubowski84  When i ran the tests i got 1 failure

```
> sbt clean test
...
23:48:18.131 [pool-7-thread-7] INFO  o.a.p.filter2.compat.FilterCompat - Filtering using predicate: eq(x, 42)
[info] Run completed in 321 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Run completed in 1 second, 259 milliseconds.
[info] Total number of tests run: 223
[info] Suites: completed 15, aborted 0
[info] Tests: succeeded 222, failed 1, canceled 0, ignored 1, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	com.github.mjakubowski84.parquet4s.ParquetSchemaResolverSpec
[error] (core / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 40 s, completed 12 Feb 2023, 11:48:19 PM
```

Also, how do I open the project in intellij? Because when i opened using sbt file it fails to detect the scala sources and test files

**Comment by mjakubowski84** [comment]
Hi @saucam.
The project should load without any issues to both IntelliJ and VS Code. The failing test is quite interesting. Which test case causes the problem?
I can only guess that you are running the project with JDK in version higher than (required) 8.

**Comment by saucam** [comment]
yes I am using java 11

```
yashdatta$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

the failing test is

```
ParquetSchemaResolverSpec
```

let me try java 8

**Comment by saucam** [comment]
@mjakubowski84 sorry for the delay in this. I have added some changes in #296 , please do take a look when you get time
