### ISSUE TITLE
Output path's for files in partition

### ISSUE THREAD

**Issue by MaksGS09** [mjakubowski84/parquet4s#273]
Hi!
I'm write partitioned parquet via fs2 stream. 
Is there a way to get the full output path (with file name included) after writing records batch?
I found several options in the `com.github.mjakubowski84.parquet4s.parquet.PostWriteHandler` but it doesn't include output path.

**Comment by mjakubowski84** [comment]
Unfortunately, file names are not exposed by PostWriteHandler. You have access only to partition path. Mind that when the batch is written more than a single file can be modified - even per partition.
