### ISSUE TITLE
Create Parquest Content As Byte Array

### ISSUE THREAD

**Issue by kirankbs** [mjakubowski84/parquet4s#274]
Hello,

First of all this library saved me not to get frustrated by reading Parquet content in Plain Scala without Spark stuff etc! Thanks!

I would like to know if there is a way to create Parquet content Byte Array from Scala Case classes without writing to file.

Context:

The azure function gets triggered with Blob trigger when the Parquet file is uploaded. The azure function receives the entire file content as Byte Array. So far so good!. The problem is writing unit tests for that function. I don't know why to just generate Byte Array with this library.

As of now I am storing a bunch of Parquet files for different scenarios in Resource older and reading them in Unit Test cases. This is very painful when I want to test many scenarios.

Please let me know if there is already a way to generate Parquet content as Byte Array or else anyway to extend the existing interface.

Thanks,
Kiran.

**Comment by mjakubowski84** [comment]
Hi!
Unfortunately, there's no support for writing files to Byte Array in Parquet4s. A long time ago, there was an external attempt on a similar topic (writing to `OutputStream`), but it had never been finalised: https://github.com/coatue-oss/parquet4s/pull/3/files.

**Comment by kirankbs** [comment]
Hello @mjakubowski84,
Thanks for the response!

Sorry if I was not clear in the explanation. I am able to read Parquet content as Byte Array using general nio files api. Such as
```
    def getParquetContent(fileName: String): Array[Byte] =
      Files
        .readAllBytes(
          Paths.get(
            getClass
              .getResource(fileName)
              .getPath
          )
        )
```

So to test my business logic at present, I had to create 10+ files to test positive and negative scenarios. I am wondering instead of having Parquet files in test resource folder, if i can
- List(ADTs) -> write As Stream -> ByteArray OR
- RowParquetRecord -> write As Stream -> Byte Array

**Comment by mjakubowski84** [comment]
Hi, 
Yes, the (unfinished) PR above is trying to deliver exactly what you want. AFAIR, people behind it wanted to send Parquet over Kafka already as a binary. This was never delivered and still missing in Parquet4s.

**Comment by mjakubowski84** [comment]
There is a support for reading and writing files from/to bytes introduced in https://github.com/mjakubowski84/parquet4s/releases/tag/v2.12.0.
