### ISSUE TITLE
Reading of files with fields of type required AND optional Int64

### ISSUE THREAD

**Issue by kazaferovic** [mjakubowski84/parquet4s#280]
Hi.

I'm trying to read parquet files that were written by Spark and contain fields of type (Scala) Long.
The problem is that the repetition_type is sometimes required and sometimes optional inside the same file/partition.
I tried defining custom classes and decoders for LongValue but can't get it to work.
Any help would be much appreciated.

**Comment by mjakubowski84** [comment]
Maybe try wrapping Long with Scala Option, e.g.:
YourClass(myLong: Option[Long])

**Comment by kazaferovic** [comment]
Thank you.
This doesn't work if the repetition_type is required.
But I found another possibility: read the parquet as generic RowParquetRecord and then get the field as Long. Drawback is that projection is not possible. But in my use-case there is no or only little performance impact.

**Comment by kazaferovic** [comment]
You are right in what I am trying to do.
ParquetReader.as[CaseClass] works even without wrapping the Long in Option and also with a case class that contains a subset of the available fields. But I assume that it is not as efficient as projection (at least theoratically)?
However that is a good enough solution. Thanks again.

**Comment by mjakubowski84** [comment]
> But I assume that it is not as efficient as projection
