### ISSUE TITLE
update to hadoop 3.3.4

### ISSUE THREAD

**Issue by anina-percipient** [mjakubowski84/parquet4s#282]
are there any plans to update parquet4s to hadoop 3.3.4 (the latest stable version)? has anyone tried this?

**Comment by mjakubowski84** [comment]
@anina-percipient Parquet4s does not come with hadoop - you have to provide it. Currently, Parquet4s is tested with hadoop 3.3.2, so I bet it works well with 3.3.4, too.

**Comment by anina-percipient** [comment]
i tried 3.3.4 and it seems to work fine for my use case at least 👍🏻
