### ISSUE TITLE
Question: How to provide Hadoop Path for reading files from S3

### ISSUE THREAD

**Issue by jeet23** [mjakubowski84/parquet4s#300]
I am trying to use the parquet-fs2 function `fromParquet` to read a file from S3.
I have set the below Hadoop configuration to read it from S3 (I am running [localstack](https://localstack.cloud/) hence the s3 url is `localhost:4566`) :
```
        val hadoopConf: Configuration = new Configuration()
        hadoopConf.set("fs.s3a.path.style.access", "true")
        hadoopConf.set("fs.s3a.endpoint.region", "eu-central-1")
        hadoopConf.set("fs.s3a.connection.ssl.enabled", "false")
        hadoopConf.set("fs.s3a.endpoint", "http://localhost:4566")
          
       val readerStream = 
            fromParquet[F]
              .as[MyCustomCaseClass]
              .options(ParquetReader.Options(hadoopConf = hadoopConf))
              .read(Path(directoryName))
```
where `directoryName` is the name of directory in S3. (In my case the directoryName = `local_directory`)

However, upon running this, I get the FileNotFound exception on [`this`](https://github.com/mjakubowski84/parquet4s/blob/master/fs2/src/main/scala/com/github/mjakubowski84/parquet4s/parquet/io.scala#L83) line.
As a result, the app bombs out with this error:
```
java.lang.IllegalArgumentException: Inconsistent partitioning.
[error] Parquet files must live in leaf directories.
[error] Every files must contain the same numbers of partitions.
[error] Partition directories at the same level must have the same names.
[error] Check following directories:
[error] 	local_directory
```

Can you please guide me on this as to why the FileNotFound exception is happening even though the file is present in the local S3?

Thanks

**Comment by jeet23** [comment]
I am now getting the following exception on actual AWS account. I'm [using](https://hadoop.apache.org/docs/current/hadoop-aws/tools/hadoop-aws/assumed_roles.html) the IAM assumed role to connect from Hadoop to AWS.

```
Failed to initialize fileystem s3a://my-bucket/my-file.parquet: java.nio.file.AccessDeniedException: : org.apache.hadoop.fs.s3a.auth.NoAwsCredentialsException: SimpleAWSCredentialsProvider: No AWS credentials in the Hadoop configuration
```

Do you have any idea on this?

**Comment by mjakubowski84** [comment]
@jeet23 Your questions are related to Hadoop AWS, not Parquet4S (which is just based on Hadoop indirectly). Please seek for a support in Hadoop community or docs.
