### ISSUE TITLE
Feature Request: scalapb support

### ISSUE THREAD

**Issue by huajiang-tubi** [mjakubowski84/parquet4s#303]
Is there existing support for scalapb in this repo or anywhere else?

**Comment by mjakubowski84** [comment]
I am not sure what you mean, but here you have an example of a writer with Protobuf schema using [sbt-protobuf](https://github.com/sbt/sbt-protobuf):

https://github.com/mjakubowski84/parquet4s/blob/master/examples/src/main/scala/com/github/mjakubowski84/parquet4s/fs2/CustomParquetWriterFS2App.scala

**Comment by huajiang-tubi** [comment]
parquet-protobuf only works with generated messages in Java. We are using akka-grpc and want to write the generated scala messages to parquet. Here is a proposal for the feature: #305

**Comment by mjakubowski84** [comment]
Hi @huajiang-tubi,
That's a nice add-on and quite an effort to implement it!

**Comment by mjakubowski84** [comment]
Support for ScalaPB released in https://github.com/mjakubowski84/parquet4s/releases/tag/v2.13.0
