### ISSUE TITLE
An example for writing a required or optional value codec for custom type with more than one field.

### ISSUE THREAD

**Issue by Eli-Golin** [mjakubowski84/parquet4s#304]
The current example for custom types is too simplistic. could you please demonstrate how to implement a `RequiredValueCodec` for 
`case class Foo(i:Int,s:String) ` ?

**Comment by mjakubowski84** [comment]
Hi @Eli-Golin!
What do you want to achieve? Why do you need a custom codec for a case class?

**Comment by jeet23** [comment]
@mjakubowski84 can you also provide an example `TypedSchemaDef` for a case class that contains optional fields.

Eg: `case class Foo(maybeValue: Option[String])`

**Comment by mjakubowski84** [comment]
@jeet23 I would like to ask the same question again. 
> What do you want to achieve? Why do you need a custom codec?

**Comment by jeet23** [comment]
Without providing the custom codec, the library throws an implicit not found error for `TypedSchemaDef`. My case class (to which I am decoding to) contains an optional field as I mentioned above.

**Comment by mjakubowski84** [comment]
You do not need to provide custom codecs for case classes, options, etc when using Parquet4s. A list of types supported out of the box is documented here: https://mjakubowski84.github.io/parquet4s/docs/records_and_schema/#supported-types. You must have a mistake in your Scala code.

**Comment by jeet23** [comment]
So, you are saying `Option`s are also supported out of the box?
