### ISSUE TITLE
Add Pekko support

### ISSUE THREAD

**Issue by mariadroman** [mjakubowski84/parquet4s#313]
Hello!

Now that Akka has changed its licence, there's an Akka fork called [Apache Pekko](https://pekko.apache.org/). Would you consider adding Pekko support to parquet4s? That will help projects that already use parquet4s with Akka to easily switch to parquet4s with Pekko.

Greetings,
Maria

**Comment by mjakubowski84** [comment]
Hi @mariadroman! I am very happy about Pekko. It makes me see the future of Scala in brighter colors.

I would love Parquet4S to support both Akka and Pekko. However, it isn't my highest priority for this project. However, I would appreciate a contribution :)

**Comment by mariadroman** [comment]
Hi @mjakubowski84 , that's great! I'll find the time for such contribution ;)
Thanks!

**Comment by utkuaydn** [comment]
Hi @mjakubowski84, we could really use this feature, can you take a look when you have some time?

**Comment by utkuaydn** [comment]
Hi, @mjakubowski84, we have integrated sbt-projectmatrix in the project for Akka and Pekko support. Feel free to take a look and comment if you feel anything needs changing :)

**Comment by mjakubowski84** [comment]
Released in v2.14.0
