### ISSUE TITLE
Is it possible to write a file without Akka or Fs2 integration?

### ISSUE THREAD

**Issue by kell18** [mjakubowski84/parquet4s#316]
Hello!

One question to documentation - is there a wayto write a file without Akka or Fs2 integration? The problem is that we use Cats 2.x in our project still and the latest Fs2 version used in Parquet4s pulls 3.x as dependency.

Best regards,
Albert

**Comment by mjakubowski84** [comment]
Yes, you can. Please read the documentation and/or examples.

**Comment by kell18** [comment]
Well... I found a a glimpse on quick start page, but without a title it was almost hidden for me, I don't use Mill and I skimmed over it. Also there are docs sections about integrations with 3rd party but not about plain basic use. Thanks anyway
