### ISSUE TITLE
ParquetSchemaResolver test fails on recent JVMs

### ISSUE THREAD

**Issue by i10416** [mjakubowski84/parquet4s#328]
A test `ParquetSchemaResolver should use default schema name when processing a class that JVM treats as malformed` fails when it runs on recent JDKs.

```
ParquetSchemaResolver should use default schema name when processing a class that JVM treats as malformed 
- "[com.github.mjakubowski84.parquet4s.ParquetSchemaResolverSpec.Malformed$.Clazz]" was not equal to "[parquet4s_schema]"
```

Recent JVM does not regard the given class as malformed here https://github.com/mjakubowski84/parquet4s/blob/6cf658a112353b2ef4accfec11da00b7e03a8b75/core/src/main/scala-2.12/com/github/mjakubowski84/parquet4s/ParquetSchemaResolver.scala#L93.

**Comment by mjakubowski84** [comment]
Yes, this test is for JDK8. Parquet4s is built by JDK8 (yes, lots of people still use JDK8), so the test checks this case. Check https://github.com/mjakubowski84/parquet4s/blob/master/.java-version
