### ISSUE TITLE
How to filter based on null in data?

### ISSUE THREAD

**Issue by egorsmth** [mjakubowski84/parquet4s#360]
How to make filter with null constrain for example with "where column1 != null" ?
`Filter.neqFilter(Col("column1"), null)` is type inconsistent, how to construct such filter?

**Comment by mjakubowski84** [comment]
Oh! I would like to say that you can cast null to a proper type using `asInstanceOf`, but still it can cause problems with, for example, Strings. That being said - lack of dedicated `isNull` and `isNotNull` filters is an oversight. I am going to add them in the upcoming release (coming this week!)

**Comment by egorsmth** [comment]
Thank you!

**Comment by mjakubowski84** [comment]
To be released in 2.20.0
