### ISSUE TITLE
Incorrect filtering of nested partitions 

### ISSUE THREAD

**Issue by egorsmth** [mjakubowski84/parquet4s#363]
Example:
part_date=2010-01-01/part_hour=10
part_date=2022-01-01/part_hour=17

filter:
AND(
  AND(GT(part_date, "2009-01-01"), GT(part_hour=9))
  AND(LT(part_date, "2023-01-01"), LT(part_hour=9))
)

result will be empty, because LT(part_hour=9) will filter out all part_hour. Is my filter wrong or this case is not supported?

**Comment by mjakubowski84** [comment]
Well, you have a logical problem here. Unrelated to Parquet4s.

Hint: Use the hour filter for boundary dates only. Do not apply it to the rest of partitions.
