### ISSUE TITLE
Support for large case classes?

### ISSUE THREAD

**Issue by mac01021** [mjakubowski84/parquet4s#80]
My case class is big (~10 fields, each is an Option[X] for a different X, where X is another case class containing 10 fields with type Option[String] or Option[Seq[String]] or Option[Y] where Y is another case class.... you get the idea)

The problem is that, when trying to resolve the schema, the scala compiler thinks the implicit expansion is divergent and aborts.

Do I have any options here besides describing the entire schema manually?

**Comment by mac01021** [comment]
This `Record` case class is the example I'm trying to write to parquet. 


      case class Record(user: Option[UserProperties],
                       app: Option[AppProperties],
                       browser: Option[BrowserProperties],
                       device: Option[DeviceProperties],
                       visitor: Option[VisitorProperties],
                       generated: Option[GeneratedProperties],
                       events: Many[EventProperties])


      type Str = Option[String]
      type Bool = Option[Boolean]
      type Int32 = Option[Int]
      type Int64 = Option[Long]
      type Float64 = Option[Double]
      type Many[V] = Option[Seq[V]]


      case class UserGuest(id: Str,
                       source: Str,
                       logged_in: Bool)
       case class UserSubscription(id: Str,
                              source: Str)
      case class UserProperties(guest_id: Many[UserGuest],
                            subscription_id: Many[UserSubscription])

      case class AppProperties(bundle_id: Str,
                           name: Str,
                           platform: Str,
                           version: Str,
                           cto_lib_version: Str,
                           region: Str,
                           country: Str)

      case class BrowserProperties(`type`: Str,
                               height: Str,
                               width: Str,
                               cookies_flag: Str,
                               local_storage_flag: Str,
                               java_flag: Str,
                               javascript_version: Str,
                               plugins: Str,
                               flash_version: Str)

      case class DeviceProperties(machine: Str,
                              os: Str,
                              os_version: Str,
                              model: Str,
                              height: Str,
                              width: Str,
                              color_depth: Str,
                              resolution: Str,
                              user_agent: Str,
                              jailbroken: Str,
                              carrier: Str,
                              manufacturer: Str)

      case class AnonymousVisitorProperties(id: Str, source: Str)

      case class ProtectedVisitorProperties(id: Str, source: Str)

      case class VisitorProperties(anonymous_id: Many[AnonymousVisitorProperties],
                               protected_id: Many[ProtectedVisitorProperties],
                               first_page: Str,
                               first_url: Str,
                               first_referrer_url: Str)

      case class GeneratedProperties(ip: Str,
                                 geo: Str,
                                 event_server_timestamp: Int64,
                                 server_host: Str,
                                 server_version: Str,
                                 event_adjusted_timestamp: Int64,
                                 fraud_confidence_score: Str)

      case class PageProperties(location: Str,
                            url: Str,
                            id: Str,
                            id_source: Str,
                            instance_id: Str,
                            referrer_url: Str,
                            z_axis: Str,
                            version: Str,
                            `type`: Str,
                            time_spent: Float64)

      case class LinkProperties(module_name: Str,
                            module_position: Str,
                            module_type: Str,
                            name: Str,
                            position: Str,
                            `type`: Str,
                            destination_location: Str,
                            destination_url: Str)

      case class RegistrationProperties(guest_id: Str,
                                    guest_id_domain: Str,
                                    flow: Str,
                                    step: Str)

       case class CustomProperties(c1: Str, c2: Str, c3: Str, c4: Str, c5: Str, c6: Str)

      case class ArticleProperties(id: Str, id_source: Str, name: Str)

      case class MediaProperties(id: Str,
                             id_source: Str,
                             name: Str,
                             indicated_bitrate: Float64,
                             observed_bitrate: Float64,
                             content_length: Float64,
                             current_position: Float64,
                             current_chapter: Str,
                             player_name: Str,
                             player_type: Str,
                             player_version: Str,
                             session_id: Str,
                             session_sequence_number: Str,
                             availability: Str,
                             previous_subtitle_language: Str,
                             subtitle_language: Str,
                             previous_audio_language: Str,
                             audio_language: Str,
                             auto: Int32,
                             `type`: Str,
                             play_type: Str,
                             current_event_value: Str,
                             next_event_value: Str,
                             playlist_id: Str,
                             playback_mode: Str,
                             ad_id: Str,
                             ad_id_source: Str,
                             time_spent: Float64)

      case class PersonalizationContentProperties(event: Str,
                                              personalized: Str,
                                              curated: Str,
                                              personalization_reason: Str,
                                              personalization_rule: Str,
                                              edition: Str,
                                              slot_position: Str,
                                              presentation_type: Str,
                                              content_id: Str,
                                              content_id_type: Str,
                                              nav_method: Str,
                                              clubhouse: Str,
                                              feed_version: Str,
                                              content_score: Int32,
                                              entitled: Str)

      case class Event(tracktype: Str,
                   name: Str,
                   instance_id: Str,
                   sequence_num: Int32,
                   app_sequence_num: Int32,
                   timestamp: Int64,
                   log_timestamp: Int64,
                   logging_source: Str,
                   online_flag: Str,
                   ab_test: Str)

      case class SessionProperties(id: Many[Str],
                               language: Str,
                               first_page: Str,
                               first_url: Str,
                               first_referrer_url: Str,
                               sequence_num: Int32,
                               language_country: Str,
                               language_original: Str,
                               start_timestamp: Int64)

      case class StateProperties(cmp: Str,
                             test: Str,
                             page_location: Str,
                             page_url: Str,
                             page_id: Str,
                             page_id_source: Str,
                             page_instance_id: Str,
                             page_referrer_url: Str,
                             page_type: Str,
                             page_location_previous: Str,
                             game_level: Str)

      case class EventProperties(event_properties: Option[Event],
                             session: Option[SessionProperties],
                             state: Option[StateProperties],
                             page: Option[PageProperties],
                             link: Option[LinkProperties],
                             registration: Option[RegistrationProperties],
                             custom: Option[CustomProperties],
                             article: Option[ArticleProperties],
                             media: Option[MediaProperties],
                             pzncon: Option[PersonalizationContentProperties],
                             unmapped: Option[Map[String, String]])

**Comment by mjakubowski84** [comment]
Hi @mac01021 
Thanks for sharing your issue here. We definitely need to look into it!
I think that large case class should not be an issue here. 10 fields is not much. Options and Options of nested classes should be fine, too. It rather looks like that you are using some type that is not supported. Unfortunately, we still do not have a docu that would list of all types that are already supported (but: you can add codecs for your type on your own in your code). Still, there are test and it tests that can give you a hint what you can use in your schema.

I see two potential culprits here:

1. Option[Seq[X]], Option[Map[X, Y]], Option[any_collection] - we are missing tests for such usage of collections, theoretically it should work but I am not 100% sure. Usually I do not put collection into Option in the model because I define missing data as empty collection rather the as None. I understand that it might be different in your case. However, if is not a problem, please try to get rid of Option here, maybe we will find the problem. And then we need to fix it.
2. Simple type aliases should not be a problem but ones with generic can: 
`type Many[V] = Option[Seq[V]]`, especially when you use it as `Many[Str]`. Compiler might have a problem with finding a proper codec for such a type. Please try using types without aliases and check if it helps.

All of those are just my guesses. I cannot validate it "in silico" now, so please check it on your own.

**Comment by mac01021** [comment]
You're right that it is not related to the size.  I found a more minimal example, which you can find in my edit above.

**Comment by mac01021** [comment]
The generic type alias seems to be fine.

As the following program demonstrates,  an option of collection of primitives works fine, but an option of collection of structs fails

    object PqSchemaTest  extends  App {

      case class Struct(int: Int, str: String)
      case class SomethingWithOptionalCollOfPrimitives(maybeStuff: Option[Seq[String]])
      case class SomethingWithOptionalCollOfStructs(maybeStuff: Option[Seq[Struct]])

      import com.github.mjakubowski84.parquet4s.ParquetSchemaResolver._

      println(resolveSchema[SomethingWithOptionalCollOfPrimitives])
      println()
      println(resolveSchema[SomethingWithOptionalCollOfStructs])

    }

**Comment by mac01021** [comment]
FYI:  Here is another example that fails, (not an optional collection this time)

    object PqSchemaTest2  extends  App {

      type Str = Option[String]
      type Bool = Option[Boolean]

      case class A(id: Str, source: Str, bool: Bool)
      case class B(id: Str, source: Str)
      case class C(as: Seq[A], bs: Seq[B])

      import com.github.mjakubowski84.parquet4s.ParquetSchemaResolver._


      println(resolveSchema[C])
      println()


    }

**Comment by mjakubowski84** [comment]
Thanks for investigation!
As `Option[Seq[String]]` works and `Seq[Struct]` works well then my guess that `ParquetSchemaResolver` is facing issue with recursive implicits resolution. This probably can be fixed by using https://www.scala-exercises.org/shapeless/lazy in proper place (I guess that will be https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/ParquetSchemaResolver.scala#L257 and similarly for collectons and maps).
If that fixes the issue in schema resolver then we might face the same issue in ValueCodecs

**Comment by mac01021** [comment]
Thanks @mjakubowski84 .

**If** I figure out how shapeless works before my boss tells me to give up and find another solution, then I'll send you a PR.  But don't wait for me because it sounds like you're far closer to the solution than I am.

**Comment by mac01021** [comment]
Having added `Lazy`  in the suggested places, and testing with


    case class A(id: Option[String], source: Option[String], bool: Option[Boolean])
    case class B(id: Option[String], source: Option[String])
    case class C(as: Seq[A], bs: Seq[B])

    import com.github.mjakubowski84.parquet4s.ParquetSchemaResolver._


    println(resolveSchema[C])

I now get

    [error] /Users/coolbema/Code/parquet4s/core/src/main/scala/mac/ImplicitRecursionTest.scala:15:10: ambiguous implicit values:
    [error]  both value stringSchema in trait SchemaDefs of type => com.github.mjakubowski84.parquet4s.ParquetSchemaResolver.TypedSchemaDef[String]
    [error]  and value charSchema in trait SchemaDefs of type => com.github.mjakubowski84.parquet4s.ParquetSchemaResolver.TypedSchemaDef[Char]
    [error]  match expected type com.github.mjakubowski84.parquet4s.SchemaDef
    [error]   println(resolveSchema[C])
    [error]          ^


It's not imediately obvious to me what parameter in what function is simultaneously satisfied by all the primitive schemadefs, but I'll keep looking for a bit.

**Comment by mjakubowski84** [comment]
I think that I know what is wrong. Take a look at ParquetRecordEncoder and ParquetRecordDecoder that share the same pattern as ParquetSchemaResolver. Each of them have `generic` function but one in ParquetSchemaResolver misses Lazy for recursive parameter. Changing *only* that should fix the issue, I hope.

**Comment by mjakubowski84** [comment]
> [error] /Users/coolbema/Code/parquet4s/core/src/main/scala/mac/ImplicitRecursionTest.scala:15:10: ambiguous implicit values:
> [error]  both value stringSchema in trait SchemaDefs of type => com.github.mjakubowski84.parquet4s.ParquetSchemaResolver.TypedSchemaDef[String]
> [error]  and value charSchema in trait SchemaDefs of type => com.github.mjakubowski84.parquet4s.ParquetSchemaResolver.TypedSchemaDef[Char]
> [error]  match expected type com.github.mjakubowski84.parquet4s.SchemaDef
> [error]   println(resolveSchema[C])
> [error]          ^
> ```
> 
Hmm... looks like that adding Lazy to collection schema def made String to be treated as collection of chars... If that is true the I hope that the compiler didn't burn your machine :)

**Comment by mjakubowski84** [comment]
@mac01021 
I created #81 that should fix your problem. I checked it using your complex example that you shared here at the very beginning and it worked. Please check if it fits all your needs. Then tomorrow I can release a new version. Many other changes piled up. It is time for a new release.

**Comment by mac01021** [comment]
You're my hero.

I can write my giant, complicated records to a parquet file and it's even loadable in my Spark SQL table.

Thanks for the help!
