### ISSUE TITLE
Support Parquet Read and Write from/to GCS 

### ISSUE THREAD

**Issue by aravindr18** [mjakubowski84/parquet4s#82]
Currently, I am working on a use-case that involves reading and writing parquet files to/from Google Cloud Storage from my Akka-stream application. 
GCS uses Cloud Storage Connector (https://github.com/GoogleCloudPlatform/bigdata-interop/tree/master/gcs) that contains the implementation for the GS File Scheme. `HadoopParquetWriter` needs setting certain Hadoop fs confs to interact with GCS (https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/gcs/INSTALL.md) 
I noticed, however, that the current implementation of the `ParquetWriter` does not pass these confs.

As a quick solution, I forked the `ParquetWriter` class and modified the `customInternalWriter` method to accept Hadoop conf as an argument. This worked beautifully. 

@mjakubowski84 Wanted to know if you think this is a reasonable approach? Do you see any potential problem with this approach? 
Happy to submit the PR if you think this is a good solution. 

Thanks

**Comment by mjakubowski84** [comment]
Hi @aravindr18!
Thanks for your interest in your library!
Let me first understand your issue. If I understand correctly you want to read and write from GS and you want to configure GS file system programmatically. Wouldn't it work for you if you would just put required properties in `core-site.xml` at your classpath (as in docu that you refer to)?
Nevertheless it might be a good idea to allow developers to optionally pass Hadoop Configuration to reader and/or writer. Your PRs are welcome :)

**Comment by aravindr18** [comment]
Hi @mjakubowski84, thanks so much for your reply! 
I tried the core-site.xml approach after submitting this issue yesterday and, this worked without requiring those additional changes :) (funny that I didn't think of doing this earlier). Using the core-site.xml is a much cleaner and more straightforward approach. 
I can submit the PR to pass these confs programmatically if you think it would add some value to the lib. Otherwise, I can just update the readme to include a section about configuring for GCS 

Thanks once again

**Comment by mjakubowski84** [comment]
I think that having the possibility to pass Hadoop configuration programmatically might be a good addon. You're very welcome to do the PR. Thanks!
