### ISSUE TITLE
Serdes functionality

### ISSUE THREAD

**Issue by tampler** [mjakubowski84/parquet4s#85]
Hello I'm reading a raw Array[Byte] and wanna reconstruct my Parquet object from it. Can I do that with current implementation ? If not, do you consider that to be a valuable contribution?

Thanks,
Boris

**Comment by mjakubowski84** [comment]
Hi Boris!

I am afraid that it is rather not possible to achieve that in straightforward way. The lib is based on official Java Parquet library. However, there's a fork of my lib where someone started to write what you request. They base their implementation on Parquet's interfaces. Unfortunately, they stopped. Please take a look: https://github.com/coatue-oss/parquet4s/pull/3.
And of course - your contribution is welcome.

**Comment by tampler** [comment]
Ok, thank you Marcin. Do you think I should use Apache Arrow instead? They seem to offer a superior support and improved functionality, compared to Parquet.

**Comment by mjakubowski84** [comment]
Hey again!

For storage I would suggest Parquet. I have better experience with it
comparing, for example, to Orc. Arrow, AFAIR, is for columnar in-memory
processing. And it is has API that talks to Parquet - both ways. Maybe this
is what you're looking for?

Cheers,
Marcin

pt., 26 lip 2019, 17:16 użytkownik Boris V.Kuznetsov <
notifications@github.com> napisał:

**Comment by tampler** [comment]
In my case, it doesn't matter, since Python guys use Parquet just to serialize Pandas and write it to Kafka...
Can you advice on Parquet/Arrow projects in Java/Scala, which support SerDes?

Thanks,
Boris

**Comment by mjakubowski84** [comment]
You can check Apache projects: Spark, Flink, Drill, Hive, Nifi.

**Comment by rtoomey-coatue** [comment]
re https://github.com/coatue-oss/parquet4s/pull/3 we've been busy with some other things internally but we'll come back to it!

**Comment by tampler** [comment]
not actual
