### ISSUE TITLE
Enabling Incremental Writes in the core API

### ISSUE THREAD

**Issue by alexklibisz** [mjakubowski84/parquet4s#88]
I have a use-case where I need to periodically append to a parquet file and then eventually close it. Right now the write method assumes you have all of your data available (or at least a reference to a single iterable). This seems like it should be fairly simple to implement by exposing the functionality of the `internalWriter`, but it doesn't seem to align well with the current `ParquetWriter` type class, which only has one method `write(path, data, options)`. IMO it would be reasonable to make `ParquetWriter` be a class like: 
```
class IncrementalParquetWriter[T: ParquetRecordEncoder : ParquetSchemaResolver](path: String, options: ParquetWriter.Options = ParquetWriter.Options()) {
  private val writer = internalWriter(new Path(path), ParquetSchemaResolver.resolveSchema[T], options)
  private val valueCodecConfiguration = options.toValueCodecConfiguration
  def write(data: Iterable[T]): Unit = data.foreach { elem =>
    writer.write(ParquetRecordEncoder.encode[T](elem, valueCodecConfiguration))
  }
  def close(): Unit = writer.close()
}
```
But that breaks the interface currently defined by the type class and AFAIK is actually impossible to implement as a type class since it takes constructor parameters. Do you have any suggestions for how this should be implemented? Should it maybe just totally side-step the type class? 

The only thing I've gotten working without totally wrecking the type class methods is the following, which feels very clunky:

```
/**
  * Type class that allows to write data which schema is represented by type <i>T</i> to given path.
  * @tparam T schema of data to write
  */
trait ParquetWriter[T] {

  /**
    * Writes data to given path.
    * @param path location where files are meant to be written
    * @param data data to write
    * @param options configuration of how Parquet files should be created and written
    */
  def write(path: String, data: Iterable[T], options: ParquetWriter.Options)

  /**
    * Instantiate a new [[IncrementalParquetWriter]]
    * @param path The path to which this writer will write
    * @param options Options for writing
    */
  def incrementalWriter(path: String, options: ParquetWriter.Options): IncrementalParquetWriter[T]

}
```

**Comment by mjakubowski84** [comment]
Hi Alex!

First I would like to thank you for interest in this library and for your wish to contribute!

I think that what you want to add is valuable.
Unfortunately, when designing the writer I didn't think of state. I would even tell I wanted to avoid it. You are right, introducing it would break current API - and we cannot do it just like that, because the library is already in use by many people. I would like to do the release with breaking changes in 1.0.0 version when all features are already there and library ends his child age. 

The only idea I have at this moment is just to add a separate trait for a new solution. We can use also Java's Closeable trait, eg.:
```
object IncrementalParquetWriter {

  def apply[T: ParquetRecordEncoder : ParquetSchemaResolver](path: String, options: ParquetWriter.Options): IncrementalParquetWriter[T] =
    new IncrementalParquetWriter[T] {
      private val writer = internalWriter(new Path(path), ParquetSchemaResolver.resolveSchema[T], options)
      private val valueCodecConfiguration = options.toValueCodecConfiguration

      override def write(data: Iterable[T]): Unit =
        data.foreach { elem =>
          writer.write(ParquetRecordEncoder.encode[T](elem, valueCodecConfiguration))
        }
      override def close(): Unit = writer.close()
    }

}

trait IncrementalParquetWriter[T] extends Closeable {

  def write(data: Iterable[T])

}
```
I would not modify existing IT tests but add a simple separate one that just checks if new incremental writer works as intended (including edge cases).

**Comment by alexklibisz** [comment]
I see. Thanks, I'll take another pass at that here in a minute. What edge cases do you have in mind here?

**Comment by mjakubowski84** [comment]
Cool!
Regarding edge cases I mean:
 * Writing with closed reader
 * Closing writer without writing anything with it.
 * Whatever else you come up :)

**Comment by alexklibisz** [comment]
Sounds good. I opened a new PR with this implementation. It's similar to my second PR but doesn't mess with all the type parameters.

**Comment by mjakubowski84** [comment]
I am merging your PR but let me do some changes to it before release. I would like to replace isClosed var to something more thread-safe.

**Comment by alexklibisz** [comment]
Great! Looking forward to the release. Closing this issue. thanks for the quick review and merge.
