### ISSUE TITLE
User supplied hadoop configuration not used in builder

### ISSUE THREAD

**Issue by darmbrus** [mjakubowski84/parquet4s#92]
Currently the Hadoop parquet reader in the `ParquetIterableImpl` is built without using the user provided configuration, therefore always building with the default configuration. I would like to update this to add the config before building.

Thanks,
David

**Comment by mjakubowski84** [comment]
Hi @darmbrus!
Thanks for notifying about the issue! And sorry that you had to to this :)
I am just about to push the fix and release a new version.

**Comment by mjakubowski84** [comment]
Fix released!

**Comment by darmbrus** [comment]
Thanks for the quick fix!
