### ISSUE TITLE
How to write in streaming fashion?

### ISSUE THREAD

**Issue by mac01021** [mjakubowski84/parquet4s#98]
I have a long-running application based on parquet4s that receives a continuous stream of records from Kafka and writes them out in large batches as parquet files.

It does not use Akka streams, but just relies on the core ParquetWriter in parquet4s.

Since the parquetwriter requires me to pass a preassembled collection containing the entire batch and I want my batches to be quite large, heap usage is problematic and flushing out a file places tremendous pressure on the garbage collector.

I have tried passing the parquetwriter a lazy stream that doesn't read the records from kafka until the parquet writer iterates over it, but this did not seem to help.

Is my use case supported?  If so, what should I do?

**Comment by mjakubowski84** [comment]
Hi @mac01021!
If Scala's Stream doesn't help then you may try splitting your large batch into smaller batches. Check recently introduced https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/IncrementalParquetWriter.scala
You should be able to write multiple batches to single file before closing.

**Comment by mac01021** [comment]
Thanks @mjakubowski84!

This looks like just what I need!

Can you provide any guidance related to the cost of a batch?  Will the file come out the same whether I write it in a few large batches vs many tiny batches?

**Comment by mjakubowski84** [comment]
Hard to tell! It is strongly correlated to the size of your entity. Performance relates also to the speed and latency of your IO. I recommend you to do a series of experiments with different setup.

**Comment by mac01021** [comment]
But does it do anything specific I should know about, like creating a new row group for every batch?

**Comment by mjakubowski84** [comment]
No, nothing differs comparing to normal writer except fact that you have to call close on your own. Row groups, pages, etc, are still created according the options provided to the reader.

**Comment by mac01021** [comment]
Awesome!  Thanks!
